// <auto-generated />
using System;
using FSH.Starter.WebApi.Harvest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.WebApi.Migrations.PostgreSQL.Harvest
{
    [DbContext(typeof(HarvestDbContext))]
    partial class HarvestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("harvest")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContractStatuses.HarvestContractStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(999)
                        .HasColumnType("character varying(999)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("character varying(99)");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasFilter("\"Deleted\" IS NULL");

                    b.ToTable("HarvestContractStatuses", "harvest");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(999)
                        .HasColumnType("character varying(999)");

                    b.Property<Guid?>("HarvestContractStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("character varying(99)");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HarvestContractStatusId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasFilter("\"Deleted\" IS NULL");

                    b.ToTable("HarvestContracts", "harvest");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContractHarvestMember", b =>
                {
                    b.Property<Guid>("HarvestContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HarvestMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("HarvestContractId", "HarvestMemberId");

                    b.HasIndex("HarvestMemberId");

                    b.ToTable("HarvestContractHarvestMember", "harvest");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestMembers.HarvestMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(999)
                        .HasColumnType("character varying(999)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("character varying(99)");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("\"Deleted\" IS NULL");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasFilter("\"Deleted\" IS NULL");

                    b.ToTable("HarvestMembers", "harvest");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContract", b =>
                {
                    b.HasOne("FSH.Starter.WebApi.Harvest.Domain.HarvestContractStatuses.HarvestContractStatus", "HarvestContractStatus")
                        .WithMany()
                        .HasForeignKey("HarvestContractStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HarvestContractStatus");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContractHarvestMember", b =>
                {
                    b.HasOne("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContract", null)
                        .WithMany("HarvestContractHarvestMembers")
                        .HasForeignKey("HarvestContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSH.Starter.WebApi.Harvest.Domain.HarvestMembers.HarvestMember", "HarvestMember")
                        .WithMany()
                        .HasForeignKey("HarvestMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarvestMember");
                });

            modelBuilder.Entity("FSH.Starter.WebApi.Harvest.Domain.HarvestContracts.HarvestContract", b =>
                {
                    b.Navigation("HarvestContractHarvestMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
