
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Harvest.Domain</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Harvest.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Core\Core.csproj" />
  </ItemGroup>
</Project>
