
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Members.Application</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Members.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\framework\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Members.Domain\Members.Domain.csproj" />
  </ItemGroup>
</Project>
