<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Migrations.PostgreSQL</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Migrations.PostgreSQL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Members\**" />
    <EmbeddedResource Remove="Members\**" />
    <None Remove="Members\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\framework\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Ranch\Ranch.Infrastructure\Ranch.Infrastructure.csproj" />
    <!-- Start Project References -->
    <!-- Start Harvest Project Reference -->
    <ProjectReference Include="..\..\modules\Harvest\Harvest.Infrastructure\Harvest.Infrastructure.csproj" />
    <!-- End Harvest Project Reference -->    
    <!-- End Project References -->
    <ProjectReference Include="..\..\modules\Todo\Todo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Catalog\" />
    <Folder Include="Identity\" />
    <Folder Include="Harvest\" />
    <Folder Include="Ranch\" />
    <!-- Start Folders -->
    <!-- Start Harvest Folder -->
    <!-- End Harvest Folder -->
    <!-- End Folders -->
    <Folder Include="Tenant\" />
    <Folder Include="Todo\" />
  </ItemGroup>
</Project>
